### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by AsciiWolf** [programmin1/Repeater-START#1]
Consider making a [Flatpak](https://flatpak.org) build of Repeater-START and publishing it on [Flathub](https://flathub.org). :-)

**Comment by programmin1** [comment]
I heard of this and tried to install once. What is the advantage and do you have experience with it?

**Comment by AsciiWolf** [comment]
Flatpak is a modern application distribution technology for Linux. It brings many advantages when compared to traditional packages. Flatpak applications are user friendly, easy to install, do not have dependency issues, work on all distributions where Flatpak is supported and can be sandboxed for better security. I personally use Flatpak for almost three years and maintain some packages on Flathub. Feel free to let me know if you have any questions or need any help.

**Comment by programmin1** [comment]
To be honest I have never built a flatpak, looking at the docs it looks like it may be fairly simple for one that is just requiring pip install modules... but osmgpsmap is not a pip install module.
https://docs.flatpak.org/en/latest/python.html

If you can point to another app/example that is using GTK and the osmgpsmap dependencies and packaging them I would say that's a good start?

**Comment by programmin1** [comment]
The .deb can already be installed on a wide variety of systems. So probably not going to be adding this anytime soon but adding some new features (like search) when I get time.

PR if you want this and want to get it started, please?
