### ISSUE TITLE
.deb installation issue

### ISSUE THREAD

**Issue by stroobandt** [programmin1/Repeater-START#2]
Hi Luke,

I am also subscribed to the Ubuntu-hams list, mostly as a lurker.

Thank you for sharing your experiencing with packaging.

I tried installing your .deb file, but unfortunately, I ran into the
following installation problem:

```
$ sudo dpkg -i repeater-start_0.3.3_all.deb

Selecting previously unselected package repeater-start.
(Reading database ... 613061 files and directories currently installed.)
Preparing to unpack repeater-start_0.3.3_all.deb ...
Unpacking repeater-start (0.3.3) ...
dpkg: dependency problems prevent configuration of repeater-start:
 repeater-start depends on gir1.2-geoclue-2.0; however:
  Package gir1.2-geoclue-2.0 is not installed.

dpkg: error processing package repeater-start (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 repeater-start
```

Attempting to run it, results in the following error:

```
$ repeaterSTART
./repeaterstart.py:25: PyGIWarning: Gtk was imported without specifying
a version first. Use gi.require_version('Gtk', '3.0') before import to
ensure that the right version gets loaded.
  from gi.repository import Gtk
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 888, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./repeaterstart.py", line 37, in <module>
    from gi.repository import Geoclue
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 127, in
find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Geoclue, introspection typelib not found
```
I hope this helps.

73 de Serge, ON4AA
https://hamwaves.com/linux.ham/

On 28/07/2020 03:52, Luke Bryan wrote:
> Greetings all,
>
> I saw your Ubuntu ham radio group and thought I would join - I maintain
> the only repeater-book-type-app for Linux and its freely available
> repeater database.
> You can see the details at http://hearham.live/repeaters
>
> I haven't worked on a PPA before but it sounds interesting. I wrote up
> some blog posts on the building of the repeaters app which you can see
> https://www.instructables.com/id/Repeater-START-Ham-Radio-Repeater-Mapping-App/
> - maybe it will be helpful for others wanting to make a basic ham radio
> application.
>
> The Repeater-START app is GPL and can be distributed in the PPA if you
> would like.
>
> Have a great week
> Luke
>
>
> _______________________________________________
> Mailing list: https://launchpad.net/~ubuntu-hams
> Post to     : ubuntu-hams@lists.launchpad.net
> Unsubscribe : https://launchpad.net/~ubuntu-hams
> More help   : https://help.launchpad.net/ListHelp

**Comment by stroobandt** [comment]
Some more information:

```
$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies.
 repeater-start : Depends: gir1.2-geoclue-2.0 but it is not installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

After installing this missing `gir1.2-geoclue-2.0` package, `repeaterSTART` ran fine.

**Comment by programmin1** [comment]
I don't know why the Geoclue would not automatically install. What os version are you on?

**Comment by stroobandt** [comment]
(X)Ubuntu 18.04.4 LTS x86_64

**Comment by programmin1** [comment]
I have installed it on Xubuntu, also Ubuntu, it works. I think you may have some old packages which is why many howtos start with "sudo apt-get update". 
Please reopen if you find the same issue installing the latest .deb update or installing on any other machine.
