### ISSUE TITLE
Publish Android App to other stores

### ISSUE THREAD

**Issue by thals1992** [programmin1/Repeater-START#4]
I found this app from a list of F-Droid repositories and it would be great if it was available from other stores like the Google Play Store or Amazon Marketplace!

**Comment by programmin1** [comment]
Why? FDroid is the best, folks should switch to Fdroid which has opensource software (or not open source software, if you choose to add some other repo).
Plus I do not feel like reading their 100-page contracts right now.

**Comment by programmin1** [comment]
Thanks for the suggestion and glad you like it - please report any other issues you note.

**Comment by programmin1** [comment]
> I found this app from a list of F-Droid repositories and it would be great if it was available from other stores like the Google Play Store or Amazon Marketplace!

FYI the Android version is now available (with a few extra premium features like GMRS) for purchase on Google Play:
https://play.google.com/store/apps/details?id=com.hearham.repeaterstartpremium
